### ISSUE TITLE
HW 1 Errors

### ISSUE THREAD

**Issue by NicholasAsirvadam** [kystyvm/IDS2024S#2]
Hello, the following are errors I have found in your first homework assignment:
1. The link you have included to the course webpage does not work.
2. The formatted Thomas Edison quote is missing at the bottom of the page.
3. You have not answered question 4.
4. You have not answered question 5.

Since this is the first assignment, you have the opportunity to earn some points back on these mistakes if you resolve these issues by the start of class on Monday.

**Comment by kystyvm** [comment]
Hi, I have resolved the errors to the best of my abilities.

Sincerely,
Fauzaan Mohammed


________________________________
From: NicholasAsirvadam ***@***.***>
Sent: 18 February 2024 10:12
To: kystyvm/IDS2024S ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kystyvm/IDS2024S] HW 1 Errors (Issue #2)


[External]

Hello, the following are errors I have found in your first homework assignment:

  1.  The link you have included to the course webpage does not work.
  2.  The formatted Thomas Edison quote is missing at the bottom of the page.
  3.  You have not answered question 4.
  4.  You have not answered question 5.

Since this is the first assignment, you have the opportunity to earn some points back on these mistakes if you resolve these issues by the start of class on Monday.
